### ISSUE TITLE
2 factor authentication error.

### ISSUE THREAD

**Issue by mjfusa** [microsoftgraph/uwp-csharp-connect-sample#14]
I'm getting an error '
```
An error occurred 

No valid client certificate found in the request. No valid certificates found in the user's certificate store. Please try again choosing a different authentication method. 
```
when attempting to login with an account that has 2 factor authentication enabled.
Steps to reproduce:
1) Build and run this sample. (Microsoft-Graph-UWP-Connect)
2) Click 'Connect'
3) Login with account that has 2 factor authentication enabled (a @Microsoft.com account for example).
4) Click 'Sign in with PIN or smartcard'
5) A message about a pop up is briefly displayed. Followed by the error mentioned above.

How can I login using my 2 factor PIN or certificate?

**Comment by jamescro** [comment]
I've been able to use this sample with MFA before. I'll look into this, but could you also try to run through the Universal Windows Platform "quick start" on this page?

https://developer.microsoft.com/en-us/graph/quick-start

The quick start delivers a preconfigured version of the sample to you, so you don't need to worry about the setup steps. If you reproduce the error with the quick start, then we can rule out any configuration issues.

**Comment by mjfusa** [comment]
James the UWP quick start is the same sample this is on this repo. I went through it anyway and reproed the problem. Can you repro? This seems to be a blocking issue for enterprises with PIN / Smartcard logins.

**Comment by jamescro** [comment]
Thanks. I wanted you to try the quick start as a way to eliminate app registration and configuration as a possible cause. Since you're seeing the same issue with the quick start, it's clear that your app registration is not the issue. 

I just ran through 2-factor authentication with this sample using my corporate account, so I haven't been able to reproduce. The auth library in the sample should be able to handle multifactor authentication. I'll follow up with someone who knows more about the auth piece to see if we can determine what's happening when you run the sample.

**Comment by jamescro** [comment]
Sorry. I can reproduce now. I'm in the habit of using the Phone option, but when I click on the Pin or Smartcard option, I see the same error. I will follow up with the owners of the auth library to see why this is happening.

**Comment by jamescro** [comment]
Just getting back to you on this. We've been able to reproduce this issue in other samples, and we've filed a bug with our OS group. This might be a regression in the OS.

**Comment by valnav** [comment]
do you have an update on this?

**Comment by rtruxal** [comment]
Any updates on this would be amazing!!

Trying to link local cert-store to flask app and am very-very stuck.

**Comment by runspired** [comment]
I can't register for phone verification for my microsoft account due to this error.

**Comment by mark-szabo** [comment]
@mjfusa @rtruxal @runspired Try enabling `Shared User Certificates` on `package.appxmanifest`'s Capabilities tab!

![image](https://user-images.githubusercontent.com/3098994/46585183-bf07b700-ca6d-11e8-9d50-aa47d311cb13.png)


Learn more: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-windows-uwp#enable-integrated-authentication-on-federated-domains-optional

**Comment by mark-szabo** [comment]
Ok, this seems to be more like a workaround than a solution...

![image](https://user-images.githubusercontent.com/3098994/46585547-946c2d00-ca72-11e8-9085-599eeec30e3f.png)

**Comment by jasonjoh** [comment]
We are archiving this sample as it is no longer being maintained. We're replacing it with a new sample which you can find here: https://github.com/microsoftgraph/msgraph-training-uwp
