### ISSUE TITLE
Not able to login with Micorsoft account

### ISSUE THREAD

**Issue by alpensturm** [microsoftgraph/uwp-csharp-connect-sample#20]
After adding the correct "ida:ClientID" from my app registration portal to the 'Application.Resources' tag and building the solution I run into the following error upon logging into my MS account:

We're unable to complete your request
Microsoft account is experiencing technical problems. Please try again later.

Any ideas how to troubleshoot this?

Thanks!

**Comment by TCPcloudDEV** [comment]
add 

**IdentityClientApp.RedirectUri = "{Custom Redirect URI}";**

after

**if (graphClient == null) {**

in AuthenticationHelper.cs file

where {Custom Redirect URI}  uri from app registration page under Native Application, it ends with ://auth

**Comment by alpensturm** [comment]
Thanks a lot for your help - that works!
