### ISSUE TITLE
Repo name doesn't indicate this is a sample

### ISSUE THREAD

**Issue by iambmelt** [microsoftgraph/uwp-csharp-connect-sample#6]
Feedback from HackNYC: the messaging around this repo is unclear. The name would seem to indicate that it is a library, but the README indicates that it is a sample.

If it is a library, we should offer a nuget pkg w/ integration instructions, etc.

Can we include something in our namespacing like `Graph.Microsoft.Sample`?

**Comment by jamescro** [comment]
Renamed and transferred the sample. This should address the potential confusions you mention.

**Comment by iambmelt** [comment]
Thank you for following up, @jamescro!
